tokens = {'block',
          'char',
          'double',
          'enum',
          'float',
          'int',
          'long',
          'struct',
          'taggedstruct',
          'taggedunion',
          'uchar',
          'uint',
          'ulong'}
